export const GET_CATS_REQUEST = "GET_CATS_REQUEST";
export const GET_CATS_SUCCESS = "GET_CATS_SUCCESS";
export const GET_CATS_FAIL = "GET_CATS_FAIL";

export const GET_SUBCATS_REQUEST = "GET_SUBCATS_REQUEST";
export const GET_SUBCATS_SUCCESS = "GET_SUBCATS_SUCCESS";
export const GET_SUBCATS_FAIL = "GET_SUBCATS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
