export const SHOW_SIDE_PANEL = "SHOW_SIDE_PANEL";
export const HIDE_SIDE_PANEL = "HIDE_SIDE_PANEL";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const LOAD_CART = "LOAD_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
